import { Section } from '@/components/layout/Section';import { SectionTitle } from '@/components/typography/SectionTitle';import { Button } from '@/components/ui/Button';import { FeatureCard,FrameworkCard,OpportunityCard,InsightCard,CaseStudyCard,StatCard,ContactCard,DeliverableCard,ValueCard,PrincipleCard } from '@/components/cards/Cards';import { cta,features,frameworks,opportunities,process,insights,cases,faqs } from '@/content/site';import { AssessmentDiagram,FrameworkDiagram,OpportunityDiagram,ProcessDiagram,TimelineDiagram } from '@/components/diagrams/Diagrams';
export function FeatureGridSection({title='چرا چکاپ',tone='white'}:{title?:string;tone?:'white'|'soft'|'tint'}){return <Section tone={tone}><SectionTitle eyebrow="چارچوب تصمیم" title={title} description="سه محور اصلی که چکاپ را از توصیه‌های پراکنده مدیریتی متمایز می‌کند."/><div className="grid gap-6 md:grid-cols-3">{features.map(([t,d,I])=><FeatureCard key={t as string} title={t as string} description={d as string} icon={I}/>)}</div></Section>}
export function FrameworkSection({tone='soft'}:{tone?:'white'|'soft'|'tint'}){return <Section tone={tone}><div className="grid items-center gap-10 lg:grid-cols-[1fr_1.1fr]"><FrameworkDiagram/><div><SectionTitle eyebrow="Framework" title="چارچوب اختصاصی چکاپ" description="از تشخیص تا اقدام، هر مرحله با زبان اجرایی و قابل پیگیری تعریف می‌شود."/><div className="grid gap-5">{frameworks.map(([t,d,I])=><FrameworkCard key={t as string} title={t as string} description={d as string} icon={I}/>)}</div></div></div></Section>}
export function OpportunitySection(){return <Section tone="tint"><SectionTitle eyebrow="Opportunity Paths" title="مسیرهای فرصت" description="فرصت‌ها فقط در بازار نیستند؛ در ساختار، تجربه و ریتم تصمیم‌گیری نیز پنهان‌اند."/><div className="grid gap-6 md:grid-cols-3">{opportunities.map(([t,d,I])=><OpportunityCard key={t as string} title={t as string} description={d as string} icon={I}/>)}</div></Section>}
export function ProcessSection({diagram=false}:{diagram?:boolean}){return <Section tone="white"><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr]">{diagram?<ProcessDiagram/>:<TimelineDiagram/>}<div><SectionTitle eyebrow="Process" title="فرآیند همکاری" description="حرکت مرحله‌به‌مرحله، شفاف و قابل بازبینی."/><div className="grid gap-4">{process.map(([n,t,d])=><div key={n} className="rounded-2xl border border-border bg-white p-5"><b className="text-primary">{n}</b><h3 className="mt-2 font-black">{t}</h3><p className="text-text-secondary">{d}</p></div>)}</div></div></div></Section>}
export function InsightsSection(){return <Section tone="soft"><SectionTitle eyebrow="Insights" title="بینش‌های مدیریتی" description="مطالب آرام، دقیق و کوتاه برای تصمیم‌های بهتر."/><div className="grid gap-6 md:grid-cols-3">{insights.map(([t,s])=><InsightCard key={t} title={t} summary={s}/>)}</div></Section>}
export function CaseStudiesSection(){return <Section tone="soft"><SectionTitle eyebrow="Evidence" title="مطالعات موردی" description="روایت‌های خلاصه از مسئله، رویکرد و نتیجه."/><div className="grid gap-6 md:grid-cols-3">{cases.map(([a,b,c,d])=><CaseStudyCard key={a} category={a} challenge={b} approach={c} outcome={d}/>)}</div></Section>}
export function DeliverablesSection(){return <Section tone="tint"><SectionTitle title="خروجی‌های قابل استفاده" description="هر همکاری باید به زبان تصمیم، اجرا و پیگیری ترجمه شود."/><div className="grid gap-6 md:grid-cols-3">{['تصویر تشخیصی','نقشه اولویت','ریتم پیگیری'].map((x)=><DeliverableCard key={x} title={x} description="خروجی روشن، قابل ارائه و قابل پیگیری برای تیم مدیریت." />)}</div></Section>}
export function FAQSection(){return <Section tone="white"><SectionTitle title="پرسش‌های رایج"/><div className="grid gap-4">{faqs.map(([q,a])=><details key={q} className="rounded-2xl border border-border p-6"><summary className="cursor-pointer font-black">{q}</summary><p className="mt-4 text-text-secondary">{a}</p></details>)}</div></Section>}
export function StatsSection(){return <Section tone="dark"><div className="grid gap-6 md:grid-cols-3"><StatCard value="۵" label="بعد ارزیابی مدیریتی"/><StatCard value="۶" label="مرحله همکاری"/><StatCard value="۳" label="خروجی اجرایی اصلی"/></div></Section>}
export function AssessmentSection(){return <Section tone="white"><div className="grid items-center gap-10 lg:grid-cols-2"><AssessmentDiagram/><SectionTitle title="ابعاد ارزیابی مدیریتی" description="چکاپ ابعاد مالی، عملیاتی، تجربه، تیم و رشد را همزمان می‌بیند تا مسئله واقعی گم نشود."/></div></Section>}
export function OpportunityMapSection(){return <Section tone="white"><OpportunityDiagram/></Section>}
export function ValuesSection(){return <Section tone="soft"><SectionTitle title="ارزش‌ها و اصول کاری"/><div className="grid gap-6 md:grid-cols-4">{['دقت','شفافیت','احترام به زمینه','پیگیری'].map(x=><ValueCard key={x} title={x} description="اصل رفتاری ثابت در همکاری‌های چکاپ." />)}</div></Section>}
export function PrinciplesSection(){return <Section tone="white"><SectionTitle title="اصول اجرایی مدیرانه"/><div className="grid gap-6 md:grid-cols-3">{['تصمیم بر اساس شواهد','کمک بدون جایگزینی تیم','ساده‌سازی بدون سطحی‌سازی'].map(x=><PrincipleCard key={x} title={x} description="اصل راهنما برای کیفیت تصمیم و اجرا." />)}</div></Section>}
export function ContactSection(){return <Section tone="soft"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-4"><ContactCard title="جلسه آشنایی" text="۳۰ تا ۴۵ دقیقه"/><ContactCard title="روش برگزاری" text="آنلاین یا حضوری در تهران"/></div><form className="grid gap-4 rounded-3xl bg-white p-8 shadow-small"><input className="rounded-xl border border-border p-4" placeholder="نام و نام خانوادگی"/><input className="rounded-xl border border-border p-4" placeholder="نام سازمان"/><input className="rounded-xl border border-border p-4" placeholder="موبایل"/><textarea className="min-h-[140px] rounded-xl border border-border p-4" placeholder="پیام"/><Button type="submit">ارسال درخواست</Button></form></div></Section>}
export function CTASection(){return <Section tone="dark"><div className="mx-auto max-w-3xl text-center"><h2 className="text-3xl font-black">{cta.title}</h2><p className="mt-5 text-white/75">{cta.text}</p><Button href="/contact" className="mt-8 bg-white text-primary hover:bg-primary-soft">درخواست جلسه</Button></div></Section>}
